# Generated by Django 2.2 on 2019-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
