# Generated by Django 2.2 on 2019-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190519_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='direct_questions_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
